name: Check Markdown links

  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
 
permissions:
  contents: read

jobs:
  markdown-link-check:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/MarkdownLinksCheck.yml@main

