name: Cross-References Check

on: 
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
 
permissions:
  contents: read

jobs:
  crossref-check-without-anchors:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/XRefCheck.yml@main